<?php

$sheet = array(
	array(
		"id" => 1,
		"Name" => "Basic Materials",
		"Image" => "1/12/Basic_Materials.png",
		"Type" => "logi",
		"PCName" => "bmats",
		"BMats" => "",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "100",
		"Points" => "20",
	),
	array(
		"id" => 2,
		"Name" => "Rifle",
		"Image" => "9/9f/Rifle.png",
		"Type" => "light",
		"PCName" => "rifle",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "8",
	),
	array(
		"id" => 3,
		"Name" => "7.62mm Rifle",
		"Image" => "2/2d/762mm.png",
		"Type" => "light",
		"PCName" => "762rifle",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "40",
		"Points" => "",
	),
	array(
		"id" => 4,
		"Name" => "Frag Grenade",
		"Image" => "f/fb/Grenade.png",
		"Type" => "heavy",
		"PCName" => "nad",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "20",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 5,
		"Name" => "HE Grenade",
		"Image" => "6/6b/HE_Grenade.png",
		"Type" => "heavy",
		"PCName" => "henad",
		"BMats" => "180",
		"RMats" => "",
		"Explos" => "40",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 6,
		"Name" => "14.5mm",
		"Image" => "2/22/14.5mm.pn",
		"Type" => "heavy",
		"PCName" => "145mm",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 7,
		"Name" => "Revolver",
		"Image" => "",
		"Type" => "light",
		"PCName" => "revolver",
		"BMats" => "60",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 8,
		"Name" => ".44 Revolver",
		"Image" => "2/26/.44.png",
		"Type" => "light",
		"PCName" => "44ammo",
		"BMats" => "40",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "40",
		"Points" => "",
	),
	array(
		"id" => 9,
		"Name" => "SMG",
		"Image" => "",
		"Type" => "light",
		"PCName" => "smg",
		"BMats" => "120",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 10,
		"Name" => "9mm SMG",
		"Image" => "",
		"Type" => "light",
		"PCName" => "9smg",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "40",
		"Points" => "",
	),
	array(
		"id" => 11,
		"Name" => "R.P.G.",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "rpg",
		"BMats" => "100",
		"RMats" => "25",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 12,
		"Name" => "R.P.G. Shell",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "rpgshell",
		"BMats" => "60",
		"RMats" => "",
		"Explos" => "75",
		"HEMats" => "",
		"Per Crate" => "15",
		"Points" => "",
	),
	array(
		"id" => 13,
		"Name" => "Anti-tank Sticky Bomb",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "sticky",
		"BMats" => "50",
		"RMats" => "",
		"Explos" => "50",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 14,
		"Name" => "Shotgun",
		"Image" => "",
		"Type" => "light",
		"PCName" => "shotgun",
		"BMats" => "120",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 15,
		"Name" => "Buckshot",
		"Image" => "",
		"Type" => "light",
		"PCName" => "buckshot",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "40",
		"Points" => "",
	),
	array(
		"id" => 16,
		"Name" => "Smoke Grenade",
		"Image" => "",
		"Type" => "light",
		"PCName" => "smoke",
		"BMats" => "120",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 17,
		"Name" => "12.7mm",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "127mm",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 18,
		"Name" => "Green Ash",
		"Image" => "d/d6/Green_Ash.png",
		"Type" => "heavy",
		"PCName" => "greenash",
		"BMats" => "140",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 19,
		"Name" => "Carbine",
		"Image" => "",
		"Type" => "light",
		"PCName" => "carbine",
		"BMats" => "140",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 20,
		"Name" => "7.62mm Carbine",
		"Image" => "",
		"Type" => "light",
		"PCName" => "762carb",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "40",
		"Points" => "",
	),
	array(
		"id" => 21,
		"Name" => "Mortar",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "mortar",
		"BMats" => "100",
		"RMats" => "25",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 22,
		"Name" => "Mortar Shell",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "mtshell",
		"BMats" => "60",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "15",
		"Per Crate" => "15",
		"Points" => "",
	),
	array(
		"id" => 23,
		"Name" => "Mortar Shrapnel Shell",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "mshrapshell",
		"BMats" => "90",
		"RMats" => "",
		"Explos" => "30",
		"HEMats" => "",
		"Per Crate" => "15",
		"Points" => "",
	),
	array(
		"id" => 24,
		"Name" => "Motar Flare Shell",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "mflareshell",
		"BMats" => "60",
		"RMats" => "",
		"Explos" => "15",
		"HEMats" => "",
		"Per Crate" => "15",
		"Points" => "",
	),
	array(
		"id" => 25,
		"Name" => "Mortar Armour Piercing Shell",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "mapshell",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "140",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 26,
		"Name" => "55mm",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "55mm",
		"BMats" => "160",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "40",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 27,
		"Name" => "Storm Rifle",
		"Image" => "",
		"Type" => "light",
		"PCName" => "storm",
		"BMats" => "",
		"RMats" => "20",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 28,
		"Name" => "7.92mm Storm",
		"Image" => "",
		"Type" => "light",
		"PCName" => "792storm",
		"BMats" => "120",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "40",
		"Points" => "",
	),
	array(
		"id" => 29,
		"Name" => "Sniper Rifle",
		"Image" => "",
		"Type" => "light",
		"PCName" => "sniper",
		"BMats" => "200",
		"RMats" => "15",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 30,
		"Name" => "7.92mm Sniper",
		"Image" => "",
		"Type" => "light",
		"PCName" => "792sniper",
		"BMats" => "150",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 31,
		"Name" => "Light Machine Gun",
		"Image" => "",
		"Type" => "light",
		"PCName" => "lmg",
		"BMats" => "",
		"RMats" => "20",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 32,
		"Name" => "Machine Gun",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "mg",
		"BMats" => "",
		"RMats" => "30",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 33,
		"Name" => "Anti-Tank Rifle",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "atr",
		"BMats" => "150",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 34,
		"Name" => "13.5mm",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "135mm",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 35,
		"Name" => "150mm",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "150mm",
		"BMats" => "200",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "100",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 36,
		"Name" => "120mm",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "120mm",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "20",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 37,
		"Name" => "120mm Smoke Shell",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "120mmsmoke",
		"BMats" => "120",
		"RMats" => "",
		"Explos" => "40",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 38,
		"Name" => "40mm Round",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "40mm",
		"BMats" => "160",
		"RMats" => "",
		"Explos" => "120",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 39,
		"Name" => "75mm Round",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "75mm",
		"BMats" => "200",
		"RMats" => "",
		"Explos" => "400",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 40,
		"Name" => "68mm AT",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "68mmat",
		"BMats" => "120",
		"RMats" => "",
		"Explos" => "120",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 41,
		"Name" => "250mm",
		"Image" => "",
		"Type" => "heavy",
		"PCName" => "bunkerbuster",
		"BMats" => "120",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "30",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 42,
		"Name" => "Shovel",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "sholve",
		"BMats" => "200",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 43,
		"Name" => "Rocket Booster",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "rocketb",
		"BMats" => "",
		"RMats" => "800",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "1",
		"Points" => "",
	),
	array(
		"id" => 44,
		"Name" => "Wrench",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "wrench",
		"BMats" => "75",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 45,
		"Name" => "Radio",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "radio",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 46,
		"Name" => "Radio Backpack",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "radiobp",
		"BMats" => "150",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 47,
		"Name" => "Bayonet",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "bayonet",
		"BMats" => "40",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 48,
		"Name" => "Binoculars",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "binos",
		"BMats" => "75",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 49,
		"Name" => "Grenade Launcher",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "nadlauncher",
		"BMats" => "10",
		"RMats" => "15",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 50,
		"Name" => "Anti-Tank Mine",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "atmine",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "10",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 51,
		"Name" => "Satchel Charge",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "satchel",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "15",
		"Per Crate" => "5",
		"Points" => "",
	),
	array(
		"id" => 52,
		"Name" => "Sledge Hammer",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "sledge",
		"BMats" => "200",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 53,
		"Name" => "Gas Mask",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "gasmask",
		"BMats" => "160",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 54,
		"Name" => "Gas Mask Filters",
		"Image" => "",
		"Type" => "tools",
		"PCName" => "gasfilters",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "20",
		"Points" => "",
	),
	array(
		"id" => 55,
		"Name" => "Construction Veh.",
		"Image" => "",
		"Type" => "",
		"PCName" => "",
		"BMats" => "85",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "1",
		"Points" => "",
	),
	array(
		"id" => 56,
		"Name" => "Barge",
		"Image" => "",
		"Type" => "",
		"PCName" => "",
		"BMats" => "",
		"RMats" => "120",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "1",
		"Points" => "",
	),
	array(
		"id" => 57,
		"Name" => "Bandages",
		"Image" => "",
		"Type" => "med",
		"PCName" => "band",
		"BMats" => "160",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "80",
		"Points" => "",
	),
	array(
		"id" => 58,
		"Name" => "First Aid Kit",
		"Image" => "",
		"Type" => "med",
		"PCName" => "firstaid",
		"BMats" => "60",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 59,
		"Name" => "Trauma Kit",
		"Image" => "",
		"Type" => "med",
		"PCName" => "trauma",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 60,
		"Name" => "Blood Plasma",
		"Image" => "",
		"Type" => "med",
		"PCName" => "blood",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "80",
		"Points" => "",
	),
	array(
		"id" => 61,
		"Name" => "Soldier Supplies",
		"Image" => "",
		"Type" => "logi",
		"PCName" => "ss",
		"BMats" => "80",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "10",
		"Points" => "",
	),
	array(
		"id" => 62,
		"Name" => "Garrison Supplies",
		"Image" => "",
		"Type" => "logi",
		"PCName" => "gs",
		"BMats" => "75",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "150",
		"Points" => "",
	),
	array(
		"id" => 63,
		"Name" => "Bunker Supplies",
		"Image" => "",
		"Type" => "logi",
		"PCName" => "bs",
		"BMats" => "75",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "150",
		"Points" => "",
	),
	array(
		"id" => 64,
		"Name" => "R-12 - Salus Ambulance",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "salus",
		"BMats" => "150",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
	array(
		"id" => 65,
		"Name" => "T3 Xiphos",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "xiphos",
		"BMats" => "",
		"RMats" => "40",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
	array(
		"id" => 66,
		"Name" => "T12 Actaeon Tankette",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "actaeon",
		"BMats" => "",
		"RMats" => "60",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
	array(
		"id" => 67,
		"Name" => "T5 Percutio",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "percutio",
		"BMats" => "",
		"RMats" => "40",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
	array(
		"id" => 68,
		"Name" => "Lance-36",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "lance36",
		"BMats" => "",
		"RMats" => "350",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
	array(
		"id" => 69,
		"Name" => "Lance-40 Halberd",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "lance40",
		"BMats" => "",
		"RMats" => "370",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
	array(
		"id" => 70,
		"Name" => "R-15 - Chariot",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "r15chariot",
		"BMats" => "100",
		"RMats" => "",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
	array(
		"id" => 71,
		"Name" => "120-68 Koronides Field Gun",
		"Image" => "",
		"Type" => "vehicals",
		"PCName" => "koronides",
		"BMats" => "",
		"RMats" => "240",
		"Explos" => "",
		"HEMats" => "",
		"Per Crate" => "",
		"Points" => "",
	),
);


?>